/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class WebCam */

#ifndef _Included_WebCam
#define _Included_WebCam
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WebCam
 * Method:    getDevices
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_WebCam_getDevices
  (JNIEnv *, jobject);

/*
 * Class:     WebCam
 * Method:    connect
 * Signature: (Ljava/lang/String;Ljava/awt/Component;)V
 */
JNIEXPORT jint JNICALL Java_WebCam_connect
  (JNIEnv *, jobject, jstring, jobject);
 /*Class: WebCam
 *Method: clipBoard
 *Signature:()void
 */  
 JNIEXPORT void JNICALL Java_WebCam_clipBoard
  (JNIEnv *, jobject,jint); 
 
					       
 JNIEXPORT jbyteArray JNICALL Java_WebCam_getImage
  (JNIEnv *env, jobject,jint);
  
  /*Class: WebCam
 *Method: disConnect
 *Signature:()void
 */  
 JNIEXPORT void JNICALL Java_WebCam_disConnect
  (JNIEnv *, jobject,jint); 

#ifdef __cplusplus
}
#endif
#endif
